/**
 * Native module bridge
 *
 * This file imports the auto-generated native module shim that provides
 * access to the native iOS (Swift) and Android (Kotlin) implementations.
 *
 * The native module is generated by expo-modules-core based on the
 * ModuleDefinition in LoqaAudioBridgeModule.swift and LoqaAudioBridgeModule.kt.
 */

import { requireNativeModule } from 'expo-modules-core';

/**
 * LoqaAudioBridgeModule native module instance
 *
 * Provides access to native functions and event emitters:
 * - startAudioStream(config): Promise<boolean>
 * - stopAudioStream(): boolean
 * - isStreaming(): boolean
 *
 * Events:
 * - onAudioSamples
 * - onStreamStatusChange
 * - onStreamError
 */
const LoqaAudioBridgeModule = requireNativeModule('LoqaAudioBridge');

export default LoqaAudioBridgeModule;
